//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaTecno.WebServicesJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsJava/", ConfigurationName="WebServicesJava.WSJava")]
    public interface WSJava {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Conexion2 del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/Conexion2Request", ReplyAction="http://wsJava/WSJava/Conexion2Response")]
        TiendaTecno.WebServicesJava.Conexion2Response Conexion2(TiendaTecno.WebServicesJava.Conexion2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/Conexion2Request", ReplyAction="http://wsJava/WSJava/Conexion2Response")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.Conexion2Response> Conexion2Async(TiendaTecno.WebServicesJava.Conexion2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Conexion del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/ConexionRequest", ReplyAction="http://wsJava/WSJava/ConexionResponse")]
        TiendaTecno.WebServicesJava.ConexionResponse Conexion(TiendaTecno.WebServicesJava.ConexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/ConexionRequest", ReplyAction="http://wsJava/WSJava/ConexionResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.ConexionResponse> ConexionAsync(TiendaTecno.WebServicesJava.ConexionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento correo del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/LoginRequest", ReplyAction="http://wsJava/WSJava/LoginResponse")]
        TiendaTecno.WebServicesJava.LoginResponse Login(TiendaTecno.WebServicesJava.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/LoginRequest", ReplyAction="http://wsJava/WSJava/LoginResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.LoginResponse> LoginAsync(TiendaTecno.WebServicesJava.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/agregarAlCarritoRequest", ReplyAction="http://wsJava/WSJava/agregarAlCarritoResponse")]
        TiendaTecno.WebServicesJava.agregarAlCarritoResponse agregarAlCarrito(TiendaTecno.WebServicesJava.agregarAlCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/agregarAlCarritoRequest", ReplyAction="http://wsJava/WSJava/agregarAlCarritoResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.agregarAlCarritoResponse> agregarAlCarritoAsync(TiendaTecno.WebServicesJava.agregarAlCarritoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/GenerarVentaRequest", ReplyAction="http://wsJava/WSJava/GenerarVentaResponse")]
        TiendaTecno.WebServicesJava.GenerarVentaResponse GenerarVenta(TiendaTecno.WebServicesJava.GenerarVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/GenerarVentaRequest", ReplyAction="http://wsJava/WSJava/GenerarVentaResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.GenerarVentaResponse> GenerarVentaAsync(TiendaTecno.WebServicesJava.GenerarVentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pregunta del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/AgregarPreguntaRequest", ReplyAction="http://wsJava/WSJava/AgregarPreguntaResponse")]
        TiendaTecno.WebServicesJava.AgregarPreguntaResponse AgregarPregunta(TiendaTecno.WebServicesJava.AgregarPreguntaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/AgregarPreguntaRequest", ReplyAction="http://wsJava/WSJava/AgregarPreguntaResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.AgregarPreguntaResponse> AgregarPreguntaAsync(TiendaTecno.WebServicesJava.AgregarPreguntaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numeroTarjeta del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/realizarPagoRequest", ReplyAction="http://wsJava/WSJava/realizarPagoResponse")]
        TiendaTecno.WebServicesJava.realizarPagoResponse realizarPago(TiendaTecno.WebServicesJava.realizarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/realizarPagoRequest", ReplyAction="http://wsJava/WSJava/realizarPagoResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.realizarPagoResponse> realizarPagoAsync(TiendaTecno.WebServicesJava.realizarPagoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento correo del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/LoginEspecialRequest", ReplyAction="http://wsJava/WSJava/LoginEspecialResponse")]
        TiendaTecno.WebServicesJava.LoginEspecialResponse LoginEspecial(TiendaTecno.WebServicesJava.LoginEspecialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/LoginEspecialRequest", ReplyAction="http://wsJava/WSJava/LoginEspecialResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.LoginEspecialResponse> LoginEspecialAsync(TiendaTecno.WebServicesJava.LoginEspecialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento correo del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/VerificarRespuestaRequest", ReplyAction="http://wsJava/WSJava/VerificarRespuestaResponse")]
        TiendaTecno.WebServicesJava.VerificarRespuestaResponse VerificarRespuesta(TiendaTecno.WebServicesJava.VerificarRespuestaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/VerificarRespuestaRequest", ReplyAction="http://wsJava/WSJava/VerificarRespuestaResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.VerificarRespuestaResponse> VerificarRespuestaAsync(TiendaTecno.WebServicesJava.VerificarRespuestaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreProvincia del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/InsertarDireccionRequest", ReplyAction="http://wsJava/WSJava/InsertarDireccionResponse")]
        TiendaTecno.WebServicesJava.InsertarDireccionResponse InsertarDireccion(TiendaTecno.WebServicesJava.InsertarDireccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/InsertarDireccionRequest", ReplyAction="http://wsJava/WSJava/InsertarDireccionResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.InsertarDireccionResponse> InsertarDireccionAsync(TiendaTecno.WebServicesJava.InsertarDireccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://wsJava/).
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/CalcularMontoTotalCompraRequest", ReplyAction="http://wsJava/WSJava/CalcularMontoTotalCompraResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TiendaTecno.WebServicesJava.CalcularMontoTotalCompraResponse CalcularMontoTotalCompra(TiendaTecno.WebServicesJava.CalcularMontoTotalCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/CalcularMontoTotalCompraRequest", ReplyAction="http://wsJava/WSJava/CalcularMontoTotalCompraResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.CalcularMontoTotalCompraResponse> CalcularMontoTotalCompraAsync(TiendaTecno.WebServicesJava.CalcularMontoTotalCompraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento correoElectronico del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/realizarTransferenciaRequest", ReplyAction="http://wsJava/WSJava/realizarTransferenciaResponse")]
        TiendaTecno.WebServicesJava.realizarTransferenciaResponse realizarTransferencia(TiendaTecno.WebServicesJava.realizarTransferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/realizarTransferenciaRequest", ReplyAction="http://wsJava/WSJava/realizarTransferenciaResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.realizarTransferenciaResponse> realizarTransferenciaAsync(TiendaTecno.WebServicesJava.realizarTransferenciaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombres del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/actualizarUsuarioRequest", ReplyAction="http://wsJava/WSJava/actualizarUsuarioResponse")]
        TiendaTecno.WebServicesJava.actualizarUsuarioResponse actualizarUsuario(TiendaTecno.WebServicesJava.actualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsJava/WSJava/actualizarUsuarioRequest", ReplyAction="http://wsJava/WSJava/actualizarUsuarioResponse")]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.actualizarUsuarioResponse> actualizarUsuarioAsync(TiendaTecno.WebServicesJava.actualizarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Conexion2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Conexion2", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.Conexion2RequestBody Body;
        
        public Conexion2Request() {
        }
        
        public Conexion2Request(TiendaTecno.WebServicesJava.Conexion2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Conexion2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Conexion2;
        
        public Conexion2RequestBody() {
        }
        
        public Conexion2RequestBody(string Conexion2) {
            this.Conexion2 = Conexion2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Conexion2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Conexion2Response", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.Conexion2ResponseBody Body;
        
        public Conexion2Response() {
        }
        
        public Conexion2Response(TiendaTecno.WebServicesJava.Conexion2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class Conexion2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public Conexion2ResponseBody() {
        }
        
        public Conexion2ResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Conexion", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.ConexionRequestBody Body;
        
        public ConexionRequest() {
        }
        
        public ConexionRequest(TiendaTecno.WebServicesJava.ConexionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConexionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Conexion;
        
        public ConexionRequestBody() {
        }
        
        public ConexionRequestBody(string Conexion) {
            this.Conexion = Conexion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConexionResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.ConexionResponseBody Body;
        
        public ConexionResponse() {
        }
        
        public ConexionResponse(TiendaTecno.WebServicesJava.ConexionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConexionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ConexionResponseBody() {
        }
        
        public ConexionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(TiendaTecno.WebServicesJava.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string correo, string clave) {
            this.correo = correo;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(TiendaTecno.WebServicesJava.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarAlCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregarAlCarrito", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.agregarAlCarritoRequestBody Body;
        
        public agregarAlCarritoRequest() {
        }
        
        public agregarAlCarritoRequest(TiendaTecno.WebServicesJava.agregarAlCarritoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class agregarAlCarritoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idUsuario;
        
        public agregarAlCarritoRequestBody() {
        }
        
        public agregarAlCarritoRequestBody(int idProducto, int idUsuario) {
            this.idProducto = idProducto;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarAlCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregarAlCarritoResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.agregarAlCarritoResponseBody Body;
        
        public agregarAlCarritoResponse() {
        }
        
        public agregarAlCarritoResponse(TiendaTecno.WebServicesJava.agregarAlCarritoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class agregarAlCarritoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public agregarAlCarritoResponseBody() {
        }
        
        public agregarAlCarritoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarVenta", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.GenerarVentaRequestBody Body;
        
        public GenerarVentaRequest() {
        }
        
        public GenerarVentaRequest(TiendaTecno.WebServicesJava.GenerarVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GenerarVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        public GenerarVentaRequestBody() {
        }
        
        public GenerarVentaRequestBody(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarVentaResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.GenerarVentaResponseBody Body;
        
        public GenerarVentaResponse() {
        }
        
        public GenerarVentaResponse(TiendaTecno.WebServicesJava.GenerarVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GenerarVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GenerarVentaResponseBody() {
        }
        
        public GenerarVentaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPreguntaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPregunta", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.AgregarPreguntaRequestBody Body;
        
        public AgregarPreguntaRequest() {
        }
        
        public AgregarPreguntaRequest(TiendaTecno.WebServicesJava.AgregarPreguntaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AgregarPreguntaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pregunta;
        
        public AgregarPreguntaRequestBody() {
        }
        
        public AgregarPreguntaRequestBody(int idUsuario, string pregunta) {
            this.idUsuario = idUsuario;
            this.pregunta = pregunta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPreguntaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPreguntaResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.AgregarPreguntaResponseBody Body;
        
        public AgregarPreguntaResponse() {
        }
        
        public AgregarPreguntaResponse(TiendaTecno.WebServicesJava.AgregarPreguntaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AgregarPreguntaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public AgregarPreguntaResponseBody() {
        }
        
        public AgregarPreguntaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class realizarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="realizarPago", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.realizarPagoRequestBody Body;
        
        public realizarPagoRequest() {
        }
        
        public realizarPagoRequest(TiendaTecno.WebServicesJava.realizarPagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class realizarPagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correoElectronico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaExpiracion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cvv;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double cantidad;
        
        public realizarPagoRequestBody() {
        }
        
        public realizarPagoRequestBody(string numeroTarjeta, string correoElectronico, string fechaExpiracion, int cvv, double cantidad) {
            this.numeroTarjeta = numeroTarjeta;
            this.correoElectronico = correoElectronico;
            this.fechaExpiracion = fechaExpiracion;
            this.cvv = cvv;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class realizarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="realizarPagoResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.realizarPagoResponseBody Body;
        
        public realizarPagoResponse() {
        }
        
        public realizarPagoResponse(TiendaTecno.WebServicesJava.realizarPagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class realizarPagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public realizarPagoResponseBody() {
        }
        
        public realizarPagoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginEspecialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginEspecial", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.LoginEspecialRequestBody Body;
        
        public LoginEspecialRequest() {
        }
        
        public LoginEspecialRequest(TiendaTecno.WebServicesJava.LoginEspecialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginEspecialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nuevaClave;
        
        public LoginEspecialRequestBody() {
        }
        
        public LoginEspecialRequestBody(string correo, string nuevaClave) {
            this.correo = correo;
            this.nuevaClave = nuevaClave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginEspecialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginEspecialResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.LoginEspecialResponseBody Body;
        
        public LoginEspecialResponse() {
        }
        
        public LoginEspecialResponse(TiendaTecno.WebServicesJava.LoginEspecialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginEspecialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public LoginEspecialResponseBody() {
        }
        
        public LoginEspecialResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarRespuestaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarRespuesta", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.VerificarRespuestaRequestBody Body;
        
        public VerificarRespuestaRequest() {
        }
        
        public VerificarRespuestaRequest(TiendaTecno.WebServicesJava.VerificarRespuestaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class VerificarRespuestaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string respuesta;
        
        public VerificarRespuestaRequestBody() {
        }
        
        public VerificarRespuestaRequestBody(string correo, string respuesta) {
            this.correo = correo;
            this.respuesta = respuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarRespuestaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarRespuestaResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.VerificarRespuestaResponseBody Body;
        
        public VerificarRespuestaResponse() {
        }
        
        public VerificarRespuestaResponse(TiendaTecno.WebServicesJava.VerificarRespuestaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class VerificarRespuestaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public VerificarRespuestaResponseBody() {
        }
        
        public VerificarRespuestaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarDireccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarDireccion", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.InsertarDireccionRequestBody Body;
        
        public InsertarDireccionRequest() {
        }
        
        public InsertarDireccionRequest(TiendaTecno.WebServicesJava.InsertarDireccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InsertarDireccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombreProvincia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombreCanton;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombreDistrito;
        
        public InsertarDireccionRequestBody() {
        }
        
        public InsertarDireccionRequestBody(int idUsuario, string nombreProvincia, string nombreCanton, string nombreDistrito) {
            this.idUsuario = idUsuario;
            this.nombreProvincia = nombreProvincia;
            this.nombreCanton = nombreCanton;
            this.nombreDistrito = nombreDistrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarDireccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarDireccionResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.InsertarDireccionResponseBody Body;
        
        public InsertarDireccionResponse() {
        }
        
        public InsertarDireccionResponse(TiendaTecno.WebServicesJava.InsertarDireccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class InsertarDireccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public InsertarDireccionResponseBody() {
        }
        
        public InsertarDireccionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularMontoTotalCompra", WrapperNamespace="http://wsJava/", IsWrapped=true)]
    public partial class CalcularMontoTotalCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idUsuario;
        
        public CalcularMontoTotalCompraRequest() {
        }
        
        public CalcularMontoTotalCompraRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularMontoTotalCompraResponse", WrapperNamespace="http://wsJava/", IsWrapped=true)]
    public partial class CalcularMontoTotalCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public decimal @return;
        
        public CalcularMontoTotalCompraResponse() {
        }
        
        public CalcularMontoTotalCompraResponse(decimal @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class realizarTransferenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="realizarTransferencia", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.realizarTransferenciaRequestBody Body;
        
        public realizarTransferenciaRequest() {
        }
        
        public realizarTransferenciaRequest(TiendaTecno.WebServicesJava.realizarTransferenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class realizarTransferenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correoElectronico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double cantidad;
        
        public realizarTransferenciaRequestBody() {
        }
        
        public realizarTransferenciaRequestBody(string correoElectronico, string password, double cantidad) {
            this.correoElectronico = correoElectronico;
            this.password = password;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class realizarTransferenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="realizarTransferenciaResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.realizarTransferenciaResponseBody Body;
        
        public realizarTransferenciaResponse() {
        }
        
        public realizarTransferenciaResponse(TiendaTecno.WebServicesJava.realizarTransferenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class realizarTransferenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public realizarTransferenciaResponseBody() {
        }
        
        public realizarTransferenciaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuario", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.actualizarUsuarioRequestBody Body;
        
        public actualizarUsuarioRequest() {
        }
        
        public actualizarUsuarioRequest(TiendaTecno.WebServicesJava.actualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clave;
        
        public actualizarUsuarioRequestBody() {
        }
        
        public actualizarUsuarioRequestBody(int idUsuario, string nombres, string apellidos, string correo, string clave) {
            this.idUsuario = idUsuario;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.correo = correo;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarUsuarioResponse", Namespace="http://wsJava/", Order=0)]
        public TiendaTecno.WebServicesJava.actualizarUsuarioResponseBody Body;
        
        public actualizarUsuarioResponse() {
        }
        
        public actualizarUsuarioResponse(TiendaTecno.WebServicesJava.actualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class actualizarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public actualizarUsuarioResponseBody() {
        }
        
        public actualizarUsuarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSJavaChannel : TiendaTecno.WebServicesJava.WSJava, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSJavaClient : System.ServiceModel.ClientBase<TiendaTecno.WebServicesJava.WSJava>, TiendaTecno.WebServicesJava.WSJava {
        
        public WSJavaClient() {
        }
        
        public WSJavaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSJavaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSJavaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSJavaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.Conexion2Response TiendaTecno.WebServicesJava.WSJava.Conexion2(TiendaTecno.WebServicesJava.Conexion2Request request) {
            return base.Channel.Conexion2(request);
        }
        
        public string Conexion2(string Conexion21) {
            TiendaTecno.WebServicesJava.Conexion2Request inValue = new TiendaTecno.WebServicesJava.Conexion2Request();
            inValue.Body = new TiendaTecno.WebServicesJava.Conexion2RequestBody();
            inValue.Body.Conexion2 = Conexion21;
            TiendaTecno.WebServicesJava.Conexion2Response retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).Conexion2(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.Conexion2Response> TiendaTecno.WebServicesJava.WSJava.Conexion2Async(TiendaTecno.WebServicesJava.Conexion2Request request) {
            return base.Channel.Conexion2Async(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.Conexion2Response> Conexion2Async(string Conexion2) {
            TiendaTecno.WebServicesJava.Conexion2Request inValue = new TiendaTecno.WebServicesJava.Conexion2Request();
            inValue.Body = new TiendaTecno.WebServicesJava.Conexion2RequestBody();
            inValue.Body.Conexion2 = Conexion2;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).Conexion2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.ConexionResponse TiendaTecno.WebServicesJava.WSJava.Conexion(TiendaTecno.WebServicesJava.ConexionRequest request) {
            return base.Channel.Conexion(request);
        }
        
        public string Conexion(string Conexion1) {
            TiendaTecno.WebServicesJava.ConexionRequest inValue = new TiendaTecno.WebServicesJava.ConexionRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.ConexionRequestBody();
            inValue.Body.Conexion = Conexion1;
            TiendaTecno.WebServicesJava.ConexionResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).Conexion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.ConexionResponse> TiendaTecno.WebServicesJava.WSJava.ConexionAsync(TiendaTecno.WebServicesJava.ConexionRequest request) {
            return base.Channel.ConexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.ConexionResponse> ConexionAsync(string Conexion) {
            TiendaTecno.WebServicesJava.ConexionRequest inValue = new TiendaTecno.WebServicesJava.ConexionRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.ConexionRequestBody();
            inValue.Body.Conexion = Conexion;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).ConexionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.LoginResponse TiendaTecno.WebServicesJava.WSJava.Login(TiendaTecno.WebServicesJava.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string correo, string clave) {
            TiendaTecno.WebServicesJava.LoginRequest inValue = new TiendaTecno.WebServicesJava.LoginRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.LoginRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.clave = clave;
            TiendaTecno.WebServicesJava.LoginResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.LoginResponse> TiendaTecno.WebServicesJava.WSJava.LoginAsync(TiendaTecno.WebServicesJava.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.LoginResponse> LoginAsync(string correo, string clave) {
            TiendaTecno.WebServicesJava.LoginRequest inValue = new TiendaTecno.WebServicesJava.LoginRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.LoginRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.clave = clave;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.agregarAlCarritoResponse TiendaTecno.WebServicesJava.WSJava.agregarAlCarrito(TiendaTecno.WebServicesJava.agregarAlCarritoRequest request) {
            return base.Channel.agregarAlCarrito(request);
        }
        
        public string agregarAlCarrito(int idProducto, int idUsuario) {
            TiendaTecno.WebServicesJava.agregarAlCarritoRequest inValue = new TiendaTecno.WebServicesJava.agregarAlCarritoRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.agregarAlCarritoRequestBody();
            inValue.Body.idProducto = idProducto;
            inValue.Body.idUsuario = idUsuario;
            TiendaTecno.WebServicesJava.agregarAlCarritoResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).agregarAlCarrito(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.agregarAlCarritoResponse> TiendaTecno.WebServicesJava.WSJava.agregarAlCarritoAsync(TiendaTecno.WebServicesJava.agregarAlCarritoRequest request) {
            return base.Channel.agregarAlCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.agregarAlCarritoResponse> agregarAlCarritoAsync(int idProducto, int idUsuario) {
            TiendaTecno.WebServicesJava.agregarAlCarritoRequest inValue = new TiendaTecno.WebServicesJava.agregarAlCarritoRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.agregarAlCarritoRequestBody();
            inValue.Body.idProducto = idProducto;
            inValue.Body.idUsuario = idUsuario;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).agregarAlCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.GenerarVentaResponse TiendaTecno.WebServicesJava.WSJava.GenerarVenta(TiendaTecno.WebServicesJava.GenerarVentaRequest request) {
            return base.Channel.GenerarVenta(request);
        }
        
        public string GenerarVenta(int idUsuario) {
            TiendaTecno.WebServicesJava.GenerarVentaRequest inValue = new TiendaTecno.WebServicesJava.GenerarVentaRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.GenerarVentaRequestBody();
            inValue.Body.idUsuario = idUsuario;
            TiendaTecno.WebServicesJava.GenerarVentaResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).GenerarVenta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.GenerarVentaResponse> TiendaTecno.WebServicesJava.WSJava.GenerarVentaAsync(TiendaTecno.WebServicesJava.GenerarVentaRequest request) {
            return base.Channel.GenerarVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.GenerarVentaResponse> GenerarVentaAsync(int idUsuario) {
            TiendaTecno.WebServicesJava.GenerarVentaRequest inValue = new TiendaTecno.WebServicesJava.GenerarVentaRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.GenerarVentaRequestBody();
            inValue.Body.idUsuario = idUsuario;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).GenerarVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.AgregarPreguntaResponse TiendaTecno.WebServicesJava.WSJava.AgregarPregunta(TiendaTecno.WebServicesJava.AgregarPreguntaRequest request) {
            return base.Channel.AgregarPregunta(request);
        }
        
        public string AgregarPregunta(int idUsuario, string pregunta) {
            TiendaTecno.WebServicesJava.AgregarPreguntaRequest inValue = new TiendaTecno.WebServicesJava.AgregarPreguntaRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.AgregarPreguntaRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.pregunta = pregunta;
            TiendaTecno.WebServicesJava.AgregarPreguntaResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).AgregarPregunta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.AgregarPreguntaResponse> TiendaTecno.WebServicesJava.WSJava.AgregarPreguntaAsync(TiendaTecno.WebServicesJava.AgregarPreguntaRequest request) {
            return base.Channel.AgregarPreguntaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.AgregarPreguntaResponse> AgregarPreguntaAsync(int idUsuario, string pregunta) {
            TiendaTecno.WebServicesJava.AgregarPreguntaRequest inValue = new TiendaTecno.WebServicesJava.AgregarPreguntaRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.AgregarPreguntaRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.pregunta = pregunta;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).AgregarPreguntaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.realizarPagoResponse TiendaTecno.WebServicesJava.WSJava.realizarPago(TiendaTecno.WebServicesJava.realizarPagoRequest request) {
            return base.Channel.realizarPago(request);
        }
        
        public string realizarPago(string numeroTarjeta, string correoElectronico, string fechaExpiracion, int cvv, double cantidad) {
            TiendaTecno.WebServicesJava.realizarPagoRequest inValue = new TiendaTecno.WebServicesJava.realizarPagoRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.realizarPagoRequestBody();
            inValue.Body.numeroTarjeta = numeroTarjeta;
            inValue.Body.correoElectronico = correoElectronico;
            inValue.Body.fechaExpiracion = fechaExpiracion;
            inValue.Body.cvv = cvv;
            inValue.Body.cantidad = cantidad;
            TiendaTecno.WebServicesJava.realizarPagoResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).realizarPago(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.realizarPagoResponse> TiendaTecno.WebServicesJava.WSJava.realizarPagoAsync(TiendaTecno.WebServicesJava.realizarPagoRequest request) {
            return base.Channel.realizarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.realizarPagoResponse> realizarPagoAsync(string numeroTarjeta, string correoElectronico, string fechaExpiracion, int cvv, double cantidad) {
            TiendaTecno.WebServicesJava.realizarPagoRequest inValue = new TiendaTecno.WebServicesJava.realizarPagoRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.realizarPagoRequestBody();
            inValue.Body.numeroTarjeta = numeroTarjeta;
            inValue.Body.correoElectronico = correoElectronico;
            inValue.Body.fechaExpiracion = fechaExpiracion;
            inValue.Body.cvv = cvv;
            inValue.Body.cantidad = cantidad;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).realizarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.LoginEspecialResponse TiendaTecno.WebServicesJava.WSJava.LoginEspecial(TiendaTecno.WebServicesJava.LoginEspecialRequest request) {
            return base.Channel.LoginEspecial(request);
        }
        
        public string LoginEspecial(string correo, string nuevaClave) {
            TiendaTecno.WebServicesJava.LoginEspecialRequest inValue = new TiendaTecno.WebServicesJava.LoginEspecialRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.LoginEspecialRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.nuevaClave = nuevaClave;
            TiendaTecno.WebServicesJava.LoginEspecialResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).LoginEspecial(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.LoginEspecialResponse> TiendaTecno.WebServicesJava.WSJava.LoginEspecialAsync(TiendaTecno.WebServicesJava.LoginEspecialRequest request) {
            return base.Channel.LoginEspecialAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.LoginEspecialResponse> LoginEspecialAsync(string correo, string nuevaClave) {
            TiendaTecno.WebServicesJava.LoginEspecialRequest inValue = new TiendaTecno.WebServicesJava.LoginEspecialRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.LoginEspecialRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.nuevaClave = nuevaClave;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).LoginEspecialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.VerificarRespuestaResponse TiendaTecno.WebServicesJava.WSJava.VerificarRespuesta(TiendaTecno.WebServicesJava.VerificarRespuestaRequest request) {
            return base.Channel.VerificarRespuesta(request);
        }
        
        public string VerificarRespuesta(string correo, string respuesta) {
            TiendaTecno.WebServicesJava.VerificarRespuestaRequest inValue = new TiendaTecno.WebServicesJava.VerificarRespuestaRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.VerificarRespuestaRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.respuesta = respuesta;
            TiendaTecno.WebServicesJava.VerificarRespuestaResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).VerificarRespuesta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.VerificarRespuestaResponse> TiendaTecno.WebServicesJava.WSJava.VerificarRespuestaAsync(TiendaTecno.WebServicesJava.VerificarRespuestaRequest request) {
            return base.Channel.VerificarRespuestaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.VerificarRespuestaResponse> VerificarRespuestaAsync(string correo, string respuesta) {
            TiendaTecno.WebServicesJava.VerificarRespuestaRequest inValue = new TiendaTecno.WebServicesJava.VerificarRespuestaRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.VerificarRespuestaRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.respuesta = respuesta;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).VerificarRespuestaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.InsertarDireccionResponse TiendaTecno.WebServicesJava.WSJava.InsertarDireccion(TiendaTecno.WebServicesJava.InsertarDireccionRequest request) {
            return base.Channel.InsertarDireccion(request);
        }
        
        public string InsertarDireccion(int idUsuario, string nombreProvincia, string nombreCanton, string nombreDistrito) {
            TiendaTecno.WebServicesJava.InsertarDireccionRequest inValue = new TiendaTecno.WebServicesJava.InsertarDireccionRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.InsertarDireccionRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.nombreProvincia = nombreProvincia;
            inValue.Body.nombreCanton = nombreCanton;
            inValue.Body.nombreDistrito = nombreDistrito;
            TiendaTecno.WebServicesJava.InsertarDireccionResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).InsertarDireccion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.InsertarDireccionResponse> TiendaTecno.WebServicesJava.WSJava.InsertarDireccionAsync(TiendaTecno.WebServicesJava.InsertarDireccionRequest request) {
            return base.Channel.InsertarDireccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.InsertarDireccionResponse> InsertarDireccionAsync(int idUsuario, string nombreProvincia, string nombreCanton, string nombreDistrito) {
            TiendaTecno.WebServicesJava.InsertarDireccionRequest inValue = new TiendaTecno.WebServicesJava.InsertarDireccionRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.InsertarDireccionRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.nombreProvincia = nombreProvincia;
            inValue.Body.nombreCanton = nombreCanton;
            inValue.Body.nombreDistrito = nombreDistrito;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).InsertarDireccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.CalcularMontoTotalCompraResponse TiendaTecno.WebServicesJava.WSJava.CalcularMontoTotalCompra(TiendaTecno.WebServicesJava.CalcularMontoTotalCompraRequest request) {
            return base.Channel.CalcularMontoTotalCompra(request);
        }
        
        public decimal CalcularMontoTotalCompra(int idUsuario) {
            TiendaTecno.WebServicesJava.CalcularMontoTotalCompraRequest inValue = new TiendaTecno.WebServicesJava.CalcularMontoTotalCompraRequest();
            inValue.idUsuario = idUsuario;
            TiendaTecno.WebServicesJava.CalcularMontoTotalCompraResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).CalcularMontoTotalCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.CalcularMontoTotalCompraResponse> TiendaTecno.WebServicesJava.WSJava.CalcularMontoTotalCompraAsync(TiendaTecno.WebServicesJava.CalcularMontoTotalCompraRequest request) {
            return base.Channel.CalcularMontoTotalCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.CalcularMontoTotalCompraResponse> CalcularMontoTotalCompraAsync(int idUsuario) {
            TiendaTecno.WebServicesJava.CalcularMontoTotalCompraRequest inValue = new TiendaTecno.WebServicesJava.CalcularMontoTotalCompraRequest();
            inValue.idUsuario = idUsuario;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).CalcularMontoTotalCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.realizarTransferenciaResponse TiendaTecno.WebServicesJava.WSJava.realizarTransferencia(TiendaTecno.WebServicesJava.realizarTransferenciaRequest request) {
            return base.Channel.realizarTransferencia(request);
        }
        
        public string realizarTransferencia(string correoElectronico, string password, double cantidad) {
            TiendaTecno.WebServicesJava.realizarTransferenciaRequest inValue = new TiendaTecno.WebServicesJava.realizarTransferenciaRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.realizarTransferenciaRequestBody();
            inValue.Body.correoElectronico = correoElectronico;
            inValue.Body.password = password;
            inValue.Body.cantidad = cantidad;
            TiendaTecno.WebServicesJava.realizarTransferenciaResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).realizarTransferencia(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.realizarTransferenciaResponse> TiendaTecno.WebServicesJava.WSJava.realizarTransferenciaAsync(TiendaTecno.WebServicesJava.realizarTransferenciaRequest request) {
            return base.Channel.realizarTransferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.realizarTransferenciaResponse> realizarTransferenciaAsync(string correoElectronico, string password, double cantidad) {
            TiendaTecno.WebServicesJava.realizarTransferenciaRequest inValue = new TiendaTecno.WebServicesJava.realizarTransferenciaRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.realizarTransferenciaRequestBody();
            inValue.Body.correoElectronico = correoElectronico;
            inValue.Body.password = password;
            inValue.Body.cantidad = cantidad;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).realizarTransferenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaTecno.WebServicesJava.actualizarUsuarioResponse TiendaTecno.WebServicesJava.WSJava.actualizarUsuario(TiendaTecno.WebServicesJava.actualizarUsuarioRequest request) {
            return base.Channel.actualizarUsuario(request);
        }
        
        public string actualizarUsuario(int idUsuario, string nombres, string apellidos, string correo, string clave) {
            TiendaTecno.WebServicesJava.actualizarUsuarioRequest inValue = new TiendaTecno.WebServicesJava.actualizarUsuarioRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.actualizarUsuarioRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.correo = correo;
            inValue.Body.clave = clave;
            TiendaTecno.WebServicesJava.actualizarUsuarioResponse retVal = ((TiendaTecno.WebServicesJava.WSJava)(this)).actualizarUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.actualizarUsuarioResponse> TiendaTecno.WebServicesJava.WSJava.actualizarUsuarioAsync(TiendaTecno.WebServicesJava.actualizarUsuarioRequest request) {
            return base.Channel.actualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiendaTecno.WebServicesJava.actualizarUsuarioResponse> actualizarUsuarioAsync(int idUsuario, string nombres, string apellidos, string correo, string clave) {
            TiendaTecno.WebServicesJava.actualizarUsuarioRequest inValue = new TiendaTecno.WebServicesJava.actualizarUsuarioRequest();
            inValue.Body = new TiendaTecno.WebServicesJava.actualizarUsuarioRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.correo = correo;
            inValue.Body.clave = clave;
            return ((TiendaTecno.WebServicesJava.WSJava)(this)).actualizarUsuarioAsync(inValue);
        }
    }
}
